### ISSUE TITLE
Token option under Provider should be optional

### ISSUE THREAD

**Issue by shauns** [chronark/terraform-provider-vercel#13]
See: https://github.com/chronark/terraform-provider-vercel/blob/main/internal/provider/provider.go#L34

(Sorry I don't really know go well enough to provide a PR! Maybe I'll get an excuse one day...)

We're using your provider and extremely happy with it so far. The Provider type requires a token, but because it's loaded from an environment variable by default, it should be optional.

### Terraform Version
0.14

### Affected Resource(s)
- provider

**Comment by chronark** [comment]
Hey @shauns sorry for being late.

That should already work actually.

the `Required` flag does not care about the origin of the token.

Can you try `VERCEL_TOKEN=xxx terraform plan`?

**Comment by shauns** [comment]
Hey - it does indeed work, but `terraform validate` fails with a warning if it's being provided solely by the environment variable

**Comment by chronark** [comment]
I'm unable to reproduce this unfortunately.

I tried both `v0.14.11` and the latest `v0.15.4` on the following file

```terraform
terraform {
  required_providers {
    vercel = {
      source = "chronark/vercel"
      version = "0.10.1"
    }
  }
}

provider "vercel" {}
```
Can you give me an example where it fails?

**Comment by chronark** [comment]
I see, you can simply provide a fake token for your validation step
`VERCEL_TOKEN=x terraform validate`

There's nothing I could change to make it optional for validation only and I'd rather not set it to optional at all because it should fail as early as possible if no token is provided.
