### ISSUE TITLE
Is there a possibility to add the url of deployed project?

### ISSUE THREAD

**Issue by tapkain** [chronark/terraform-provider-vercel#5]
Hi, first of all, I'm really grateful for this package, awesome work!
I want to specify a cname on cloudflare for the deployed IP address and wondering if there is a possibility to retrieve that?

**Comment by chronark** [comment]
Hey @tapkain , thank  you for using or considering this provider.

Getting the IP for a deployment is not possible, See [here](https://vercel.com/support/articles/how-to-allowlist-deployment-ip-address)

Getting the domain for a deployment is possible though.
I just checked the [docs](https://vercel.com/docs/api#endpoints/deployments) and the `deployments` endpoint actually gives you a url back.
However I am not entirely sure yet how that could be useful.

This provider does not handle deployments yet as I did not see a use for them. Usually you want to deploy automatically via git.
So if you want to create records for each pull request deployment, then that is going to be tricky I believe.

I'd be happy to implement the domains endpoint later this week. I just haven't gotten around to it yet.
Then you can set an alias for your domain and use that as CNAME in the cloudflare provider.

Let me know if that helps you :)

**Comment by chronark** [comment]
Actually there is another way.
If your project already has deployments, then they can be retrieved via the aliases.

I will expose them as `alias` on the vercel_project` resource.

they look like this: 
```json
"alias": [
        "mercury-gamma.vercel.app",
        "mercury-chronark.vercel.app",
        "mercury-git-main-chronark.vercel.app"
      ]
      ```
      
Keep in mind that they will be empty when first creating a project and you would have to run terraform again after there has been a deployment. Would that still help you with your problem?

**Comment by tapkain** [comment]
Yeah, I think that's a great start to tackle this problem, that would work. Thank you!

**Comment by chronark** [comment]
I just released [v0.6.0](https://registry.terraform.io/providers/chronark/vercel/latest) to expose the aliases.
I was actually wrong and there is an alias already defined right after project creation. It just leads to a 404 page until the project has been deployed.

You should be able to use it like this

```terraform

resource "cloudflare_record" "xyz" {
  name    = "vercel"
  value   = vercel_project.my_project.alias[0]
  type    = "C"
  zone_id = <YOUR_ZONE_ID>

}
```

**Comment by chronark** [comment]
@tapkain  Please try it and let me know if that works or what features you'd need for your use case.

**Comment by chronark** [comment]
I'll close this, please open a new issue if you need more features
