### ISSUE TITLE
No `darwin_arm64` release?

### ISSUE THREAD

**Issue by fr3fou** [chronark/terraform-provider-vercel#50]
Hi, I'm trying to use this on my M1 MacBook Pro and I get this error
```
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/chronark/vercel v0.14.0 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms
│ supported.
```

I looked at the `.goreleaser.yaml` file but I can't seem to find anything wrong with it that'd be ignoring `darwin_arm64`. Could you take a look too?

**Comment by chronark** [comment]
@fr3fou Looks like go 0.14 did not build on darwin-arm64.
I upgrade to 0.16 and there should be darwin arm64 builds starting with [v0.14.2](https://github.com/chronark/terraform-provider-vercel/releases/tag/v0.14.2)

**Comment by carlos-alberto** [comment]
Hey @chronark looks like something went wrong with v0.14.3, the darwin_arm64 release is missing [here](https://github.com/chronark/terraform-provider-vercel/releases).

**Comment by chronark** [comment]
@carlos-alberto I'm sorry, please use [v0.14.4](https://github.com/chronark/terraform-provider-vercel/releases/tag/v0.14.4)
